In [ ]:
XGBoost Algorithm

XGBoost is a supervised Learning Algorithm which is used for both classification and regression algorithm.

XGBoost - Extreme Gradient Boosting

It is a powerful and efficient implementation of the gradient boosting framework. 
Due to improvement of its performance and speed XGBoost is used for both Regression and Classification algorithms.

In [ ]:
Key Features of XGBoost Algorithm

1) Gradient Boosting Frameworks
2) Regularization
3) Handling processing
4) Parallel Processing
5) Tree Pruning
6) Flexible

In [ ]:
Implementation of XGBoost Algorithm using Python

In [1]:
import pandas as pd
a=pd.read_csv('diabetes.csv')
display(a)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
from sklearn.model_selection import train_test_split
x=a[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]
y=a['Outcome']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
import xgboost as xgb
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
b=xgb.DMatrix(x_train,label=y_train)
c=xgb.DMatrix(x_test,label=y_test)
params={
    'objective':'multi:softmax',
    'num_class':len(y.unique()),
    'max_depth':3,
    'eta':0.1,
    'seed':42
}
num_round=100
d=xgb.train(params,b,num_round)
y_pred=d.predict(c)
accuracy=accuracy_score(y_test,y_pred)
classification=classification_report(y_test,y_pred)
confusion_matrix=confusion_matrix(y_test,y_pred)
print("Accuracy:\n",accuracy)
print("Classification_Report:\n",classification)
print("Confusion_Matrix:\n",confusion_matrix)

Accuracy:
 0.7597402597402597
Classification_Report:
               precision    recall  f1-score   support

           0       0.82      0.80      0.81        99
           1       0.66      0.69      0.67        55

    accuracy                           0.76       154
   macro avg       0.74      0.74      0.74       154
weighted avg       0.76      0.76      0.76       154

Confusion_Matrix:
 [[79 20]
 [17 38]]


In [15]:
import xgboost as xgb
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
params = {
    'objective': 'multi:softmax',  
    'num_class': 3,                 
    'max_depth': 3,       
    'eta': 0.1, 
    'seed': 42   
}
num_round = 100
bst = xgb.train(params, dtrain, num_round)
y_pred = bst.predict(dtest)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:\n',accuracy)
b=classification_report(y_test,y_pred)
print("çlassification:\n",b)
c=confusion_matrix(y_test,y_pred)
print('confusion_matrix:\n',c)

Accuracy:
 1.0
çlassification:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 
data = pd.read_csv('your_dataset.csv')
print(data.head())
X = data.iloc[:, :-1]  
y = data.iloc[:, -1] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
params = {
    'objective': 'multi:softmax',  
    'num_class': len(y.unique()),   
    'max_depth': 3,                 
    'eta': 0.1,                     
    'seed': 42                      
}
num_round = 100
bst = xgb.train(params, dtrain, num_round)
y_pred = bst.predict(dtest)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')